# Generated by Django 4.0.5 on 2022-06-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=20, unique=True, verbose_name='카테고리 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actorname', models.CharField(max_length=20, unique=True, verbose_name='성우이름')),
                ('writer', models.CharField(max_length=20, verbose_name='제작자')),
                ('voice', models.ImageField(upload_to='%Y/%m/%d')),
                ('category', models.ManyToManyField(default='카테고리 없음', to='actor.category', verbose_name='카테고리')),
            ],
        ),
    ]
